# Imagem base oficial do Python
FROM python:3.11-slim

# Define diretório de trabalho
WORKDIR /app

# Copia requirements e instala dependências
COPY infra/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código da API
COPY src/ ./src
COPY bucket/ ./bucket

# Expõe a porta
EXPOSE 5050

# Comando para rodar a API com Uvicorn
CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "5050"]
